spring:
  application:
    name: crud-basico-prototipo

  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  secret: idealcomputer_esta_e_uma_chave_secreta_muito_maior_e_mais_segura_para_usar_em_producao_2025
  expiration: 36000000

logging:
  level:
    root: INFO
    com.idealcomputer: DEBUG